name: Setup Playwright
description: Installs Playwright and Caches Browsers

runs:
  using: 'composite'
  steps:
    - name: Store Playwright's Version
      shell: bash
      run: |
        echo "PLAYWRIGHT_VERSION=$(node -e "process.stdout.write(require('@playwright/test/package.json').version)")" >> "$GITHUB_OUTPUT"
      id: playwright-version
    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps
    - name: Install Playwright Dependencies
      if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      shell: bash
      run: npx playwright install-deps
