name: Quality Gates

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize Workflow
        uses: ./.github/actions/init-workflow
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
      - name: Run E2E Tests
        shell: bash
        run: pnpm e2e
